### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by martin-ueding** [nilsleiffischer/texfig#1]
This project does not have any license, therefore one is not allowed to use this code, in a strict sense.

It would be nice if you could choose a license such that one could use this code and contribute to it.

If you don't care what people do with your code, then I'd recommend the MIT/Expat license or the BSD-2-Clause license.

**Comment by nilsleiffischer** [comment]
Hi Martin, you are absolutely right, I added a license and tagged a release with a DOI.
Thanks for your comment,
Nils
